name: Continuous Integration Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: 'Build Nextjs application'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: 'Checkout repository'

      - name: 'Install dependencies'
        run: npm install
        shell: bash

      - name: 'Build application'
        run: npm run build
        shell: bash
